### ISSUE TITLE
New controller not doing anything

### ISSUE THREAD

**Issue by rhannink** [trainman419/bekant#8]
Hello, 
I have built a LIN controller as shown in the schematic. I only use an mcp2003 e/p instead off an MCP2003B.
I have the Bekant desk plugged in with the original controller, next I remove the original controller an plug in the Arduino controller still with the Bekant desk powered on.

The desk does not respons to and button press. I see the Arduino Led lightning up when I press a button. I have also connected a logic analyser to the RX and TX pin (0 and 1) and I see LIN protocols going by. I think I even see LIN respons to ID 0x08 and LIN respons to ID 0x09.

And idea what i might be doing wrong or how I can do further debugging?

Gr. Remco

`
<img width="1012" alt="response-to-08" src="https://user-images.githubusercontent.com/1661824/117146387-71ce5c00-adb4-11eb-9cd6-02bd291362de.png">
<img width="1034" alt="response-to-09" src="https://user-images.githubusercontent.com/1661824/117146418-78f56a00-adb4-11eb-9be1-63d39fd4233f.png">

`

**Comment by trainman419** [comment]
See #2 .
